"""empty message

Revision ID: 1532a887525b
Revises: 4b21c79cbd86
Create Date: 2025-03-27 12:19:33.716659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1532a887525b'
down_revision: Union[str, None] = '4b21c79cbd86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('front_passport_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('back_passport_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('front_passport_path', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('back_passport_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'back_passport_path')
    op.drop_column('users', 'front_passport_path')
    op.drop_column('users', 'back_passport_id')
    op.drop_column('users', 'front_passport_id')
    # ### end Alembic commands ###
