"""empty message

Revision ID: 1b3e7f319410
Revises: e9dccb33182a
Create Date: 2025-05-22 12:49:33.666105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b3e7f319410'
down_revision: Union[str, None] = 'e9dccb33182a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', postgresql.ARRAY(sa.VARCHAR(length=255)), server_default='{}', nullable=False))
    op.drop_column('roles', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###
