"""empty message

Revision ID: 3d0c9c32cd6b
Revises: 6e67b30341a3
Create Date: 2025-06-02 17:15:20.449851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0c9c32cd6b'
down_revision: Union[str, None] = '6e67b30341a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'resumes', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_column('resumes', 'role_id')
    # ### end Alembic commands ###
