"""empty message

Revision ID: 434d0ff2d641
Revises: a859127e1a25
Create Date: 2025-06-01 12:38:58.002052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434d0ff2d641'
down_revision: Union[str, None] = 'a859127e1a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_sessions', sa.Column('auth_provider_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'auth_sessions', 'auth_providers', ['auth_provider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_sessions', type_='foreignkey')
    op.drop_column('auth_sessions', 'auth_provider_id')
    # ### end Alembic commands ###
