"""empty message

Revision ID: 4b21c79cbd86
Revises: e1ead4d6b9a5
Create Date: 2025-03-22 18:30:18.690014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b21c79cbd86'
down_revision: Union[str, None] = 'e1ead4d6b9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_path', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('photo_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_id')
    op.drop_column('users', 'photo_path')
    # ### end Alembic commands ###
