"""empty message

Revision ID: 614904bc1b07
Revises: e48f0abac9ee
Create Date: 2025-06-01 14:17:17.661287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '614904bc1b07'
down_revision: Union[str, None] = 'e48f0abac9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agencies', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('agencies', sa.Column('address', sa.String(length=255), nullable=False))
    op.drop_column('agencies', 'address_ky')
    op.drop_column('agencies', 'address_ru')
    op.drop_column('agencies', 'address_en')
    op.drop_column('agencies', 'title_ky')
    op.drop_column('agencies', 'title_ru')
    op.drop_column('agencies', 'title_tr')
    op.drop_column('agencies', 'address_tr')
    op.drop_column('agencies', 'title_en')
    op.add_column('companies', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('companies', sa.Column('address', sa.String(length=255), nullable=False))
    op.drop_column('companies', 'address_ky')
    op.drop_column('companies', 'address_ru')
    op.drop_column('companies', 'address_en')
    op.drop_column('companies', 'title_ky')
    op.drop_column('companies', 'title_ru')
    op.drop_column('companies', 'title_tr')
    op.drop_column('companies', 'address_tr')
    op.drop_column('companies', 'title_en')
    op.add_column('job_postings', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('job_postings', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('job_postings', 'description_ky')
    op.drop_column('job_postings', 'description_ru')
    op.drop_column('job_postings', 'title_ru')
    op.drop_column('job_postings', 'title_ky')
    op.drop_column('job_postings', 'title_tr')
    op.drop_column('job_postings', 'title_en')
    op.drop_column('job_postings', 'description_en')
    op.drop_column('job_postings', 'description_tr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('description_tr', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('job_postings', sa.Column('description_en', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('job_postings', sa.Column('title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('job_postings', sa.Column('title_tr', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('job_postings', sa.Column('title_ky', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('job_postings', sa.Column('title_ru', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('job_postings', sa.Column('description_ru', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('job_postings', sa.Column('description_ky', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('job_postings', 'description')
    op.drop_column('job_postings', 'title')
    op.add_column('companies', sa.Column('title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('address_tr', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('title_tr', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('title_ru', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('title_ky', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('address_en', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('address_ru', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('address_ky', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'title')
    op.add_column('agencies', sa.Column('title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('agencies', sa.Column('address_tr', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('agencies', sa.Column('title_tr', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('agencies', sa.Column('title_ru', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('agencies', sa.Column('title_ky', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('agencies', sa.Column('address_en', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('agencies', sa.Column('address_ru', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('agencies', sa.Column('address_ky', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('agencies', 'address')
    op.drop_column('agencies', 'title')
    # ### end Alembic commands ###
