"""empty message

Revision ID: 810022863d8c
Revises: 1380f7a9a50d
Create Date: 2025-05-29 19:04:54.984559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810022863d8c'
down_revision: Union[str, None] = '1380f7a9a50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agencies', sa.Column('address', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agencies', 'address')
    # ### end Alembic commands ###
