"""empty message

Revision ID: 86ef9fb217be
Revises: c6671268686f
Create Date: 2025-06-05 19:27:50.410934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ef9fb217be'
down_revision: Union[str, None] = 'c6671268686f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workers', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_column('workers', 'category_id')
    # ### end Alembic commands ###
