"""empty message

Revision ID: a859127e1a25
Revises: 0952431b677c
Create Date: 2025-05-30 18:29:15.710235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a859127e1a25'
down_revision: Union[str, None] = '0952431b677c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('title_ru', sa.String(length=255), nullable=False))
    op.add_column('job_postings', sa.Column('title_en', sa.String(length=255), nullable=False))
    op.add_column('job_postings', sa.Column('title_ky', sa.String(length=255), nullable=False))
    op.add_column('job_postings', sa.Column('title_tr', sa.String(length=255), nullable=False))
    op.add_column('job_postings', sa.Column('description_ru', sa.Text(), nullable=True))
    op.add_column('job_postings', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('job_postings', sa.Column('description_ky', sa.Text(), nullable=True))
    op.add_column('job_postings', sa.Column('description_tr', sa.Text(), nullable=True))
    op.drop_column('job_postings', 'description')
    op.drop_column('job_postings', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('job_postings', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('job_postings', 'description_tr')
    op.drop_column('job_postings', 'description_ky')
    op.drop_column('job_postings', 'description_en')
    op.drop_column('job_postings', 'description_ru')
    op.drop_column('job_postings', 'title_tr')
    op.drop_column('job_postings', 'title_ky')
    op.drop_column('job_postings', 'title_en')
    op.drop_column('job_postings', 'title_ru')
    # ### end Alembic commands ###
