"""empty message

Revision ID: abc97655f376
Revises: 614904bc1b07
Create Date: 2025-06-02 16:04:01.695790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abc97655f376'
down_revision: Union[str, None] = '614904bc1b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('roles', sa.Column('role', sa.String(length=255), nullable=False))
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', postgresql.ARRAY(sa.VARCHAR(length=255)), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))
    op.drop_column('roles', 'role')
    op.alter_column('job_postings', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
