"""empty message

Revision ID: b4fa46baa521
Revises: 3d0c9c32cd6b
Create Date: 2025-06-02 17:45:30.594191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4fa46baa521'
down_revision: Union[str, None] = '3d0c9c32cd6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_steps',
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_steps_id'), 'worker_steps', ['id'], unique=False)
    op.add_column('workers', sa.Column('agency_id', sa.Integer(), nullable=False))
    op.add_column('workers', sa.Column('level', sa.Integer(), server_default='0', nullable=False))
    op.add_column('workers', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('workers_job_posting_id_fkey', 'workers', type_='foreignkey')
    op.drop_constraint('workers_agent_id_fkey', 'workers', type_='foreignkey')
    op.drop_constraint('workers_job_offer_id_fkey', 'workers', type_='foreignkey')
    op.create_foreign_key(None, 'workers', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workers', 'agent_id')
    op.drop_column('workers', 'hired_at')
    op.drop_column('workers', 'comment')
    op.drop_column('workers', 'status')
    op.drop_column('workers', 'job_offer_id')
    op.drop_column('workers', 'job_posting_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('job_posting_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('workers', sa.Column('job_offer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('workers', sa.Column('status', postgresql.ENUM('pending', 'hired', 'rejected', 'active', 'resigned', 'terminated', 'completed', name='workerstatusenum'), autoincrement=False, nullable=False))
    op.add_column('workers', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('hired_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.create_foreign_key('workers_job_offer_id_fkey', 'workers', 'job_offers', ['job_offer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('workers_agent_id_fkey', 'workers', 'companies', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('workers_job_posting_id_fkey', 'workers', 'job_postings', ['job_posting_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workers', 'payload')
    op.drop_column('workers', 'level')
    op.drop_column('workers', 'agency_id')
    op.drop_index(op.f('ix_worker_steps_id'), table_name='worker_steps')
    op.drop_table('worker_steps')
    # ### end Alembic commands ###
