"""empty message

Revision ID: c6671268686f
Revises: 7e55a0349797
Create Date: 2025-06-04 15:48:38.902111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6671268686f'
down_revision: Union[str, None] = '7e55a0349797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('source_language', sa.String(length=255), nullable=True),
    sa.Column('target_language', sa.String(length=255), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_language', 'target_language', 'source_text', name='uq_translation_key')
    )
    op.create_index('ix_translation_lookup', 'translations', ['source_language', 'target_language', 'source_text'], unique=False)
    op.create_index(op.f('ix_translations_id'), 'translations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_id'), table_name='translations')
    op.drop_index('ix_translation_lookup', table_name='translations')
    op.drop_table('translations')
    # ### end Alembic commands ###
