"""empty message

Revision ID: d00d483086b9
Revises: e95cc20e0143
Create Date: 2025-05-26 15:13:58.001273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00d483086b9'
down_revision: Union[str, None] = 'e95cc20e0143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('resumes', sa.Column('last_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'last_name')
    op.drop_column('resumes', 'first_name')
    # ### end Alembic commands ###
