"""empty message

Revision ID: e1ead4d6b9a5
Revises: f820c460366c
Create Date: 2025-03-22 17:21:24.147258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ead4d6b9a5'
down_revision: Union[str, None] = 'f820c460366c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('marital_status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'marital_status')
    op.drop_column('users', 'summary')
    # ### end Alembic commands ###
