"""empty message

Revision ID: e381dab2c476
Revises: 810022863d8c
Create Date: 2025-05-30 12:12:44.206468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e381dab2c476'
down_revision: Union[str, None] = '810022863d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agencies', sa.Column('title_ru', sa.String(length=255), nullable=False))
    op.add_column('agencies', sa.Column('title_en', sa.String(length=255), nullable=False))
    op.add_column('agencies', sa.Column('title_ky', sa.String(length=255), nullable=False))
    op.add_column('agencies', sa.Column('title_tr', sa.String(length=255), nullable=False))
    op.add_column('agencies', sa.Column('address_ru', sa.String(length=255), nullable=False))
    op.add_column('agencies', sa.Column('address_en', sa.String(length=255), nullable=False))
    op.add_column('agencies', sa.Column('address_ky', sa.String(length=255), nullable=False))
    op.add_column('agencies', sa.Column('address_tr', sa.String(length=255), nullable=False))
    op.drop_column('agencies', 'title')
    op.drop_column('agencies', 'address')
    op.add_column('categories', sa.Column('title_ru', sa.String(length=255), nullable=False))
    op.add_column('categories', sa.Column('title_en', sa.String(length=255), nullable=False))
    op.add_column('categories', sa.Column('title_ky', sa.String(length=255), nullable=False))
    op.add_column('categories', sa.Column('title_tr', sa.String(length=255), nullable=False))
    op.drop_column('categories', 'title')
    op.add_column('companies', sa.Column('title_ru', sa.String(length=255), nullable=False))
    op.add_column('companies', sa.Column('title_en', sa.String(length=255), nullable=False))
    op.add_column('companies', sa.Column('title_ky', sa.String(length=255), nullable=False))
    op.add_column('companies', sa.Column('title_tr', sa.String(length=255), nullable=False))
    op.add_column('companies', sa.Column('address_ru', sa.String(length=255), nullable=False))
    op.add_column('companies', sa.Column('address_en', sa.String(length=255), nullable=False))
    op.add_column('companies', sa.Column('address_ky', sa.String(length=255), nullable=False))
    op.add_column('companies', sa.Column('address_tr', sa.String(length=255), nullable=False))
    op.drop_column('companies', 'title')
    op.drop_column('companies', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('companies', 'address_tr')
    op.drop_column('companies', 'address_ky')
    op.drop_column('companies', 'address_en')
    op.drop_column('companies', 'address_ru')
    op.drop_column('companies', 'title_tr')
    op.drop_column('companies', 'title_ky')
    op.drop_column('companies', 'title_en')
    op.drop_column('companies', 'title_ru')
    op.add_column('categories', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('categories', 'title_tr')
    op.drop_column('categories', 'title_ky')
    op.drop_column('categories', 'title_en')
    op.drop_column('categories', 'title_ru')
    op.add_column('agencies', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('agencies', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('agencies', 'address_tr')
    op.drop_column('agencies', 'address_ky')
    op.drop_column('agencies', 'address_en')
    op.drop_column('agencies', 'address_ru')
    op.drop_column('agencies', 'title_tr')
    op.drop_column('agencies', 'title_ky')
    op.drop_column('agencies', 'title_en')
    op.drop_column('agencies', 'title_ru')
    # ### end Alembic commands ###
