"""empty message

Revision ID: e48f0abac9ee
Revises: 434d0ff2d641
Create Date: 2025-06-01 14:04:06.736628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e48f0abac9ee'
down_revision: Union[str, None] = '434d0ff2d641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('companies_category_id_fkey', 'companies', type_='foreignkey')
    op.drop_column('companies', 'category_id')
    op.drop_index('ix_categories_id', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('companies_category_id_fkey', 'companies', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_table('categories',
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resume_fields', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_disabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('title_ru', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title_ky', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title_tr', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name='categories_parent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    # ### end Alembic commands ###
